Vulnerabilities = function() {
	console.log("Building list of vulnerabilities");
	const vArray =
		[
			{ "name": "S AT", "type": "string", "value": "S @", "options": "-inr" },
			{ "name": "S AT_UPD", "type": "string", "value": "S @UPDARRAY", "options": "-inr" },
			{ "name": "D_UPD_GMPLUTL", "type": "string", "value": "D UPDATE^GMPLUTL", "options": "-inr" },
			{ "name": "Reference", "type": "string", "value": "Reference", "options": "-inr" },
			{ "name": "ORQQPL", "type": "string", "value": "ORQQPL", "options": "-inr" },
			{ "name": "ACCESS", "type": "string", "value": "ACCESS", "options": "-inr" },
			{ "name": "VERIFY", "type": "string", "value": "VERIFY", "options": "-inr" },
			{ "name": "XUS_XWB^", "type": "string", "value": "^XUS^XWB^", "options": "-inr" },
			{ "name": "CHKPRMIT", "type": "string", "value": "CHKPRMIT", "options": "-inr" },
			{ "name": "CHK_XQCS", "type": "string", "value": "$$CHK^XQCS", "options": "-inr" },
			{ "name": "XQCS", "type": "string", "value": "XQCS", "options": "-inr" },
			{ "name": "XWBSEC", "type": "string", "value": "XWBSEC", "options": "-inr" },
			{ "name": "XUS ", "type": "string", "value": "XUS SIGNON", "options": "-inr" },
			{ "name": "GMPLX1", "type": "string", "value": "GMPLX1", "options": "-inr" },
			{ "name": "ORCPROB", "type": "string", "value": "ORCPROB", "options": "-inr" },
			{ "name": "ORQQPL1", "type": "string", "value": "ORQQPL1", "options": "-inr" },
			{ "name": "PXAIPL", "type": "string", "value": "PXAIPL", "options": "-inr" },
			{ "name": "PXCAPL1", "type": "string", "value": "PXCAPL1", "options": "-inr" },
			{ "name": "PXCAPL2", "type": "string", "value": "PXCAPL2", "options": "-inr" },
			{ "name": "VA_200_DUZ_0", "type": "string", "value": "^VA(200,DUZ,0)", "options": "-inr" },
			{ "name": "VA_200_DUZ_1", "type": "string", "value": "^VA(200,DUZ,.1)", "options": "-inr" },
			{ "name": "D_UPDATE_FILE", "type": "string", "value": "D UPDATE^ - FILE^", "options": "-inr" },
			{ "name": "SET_AT", "type": "string", "value": "SET @", "options": "-inr" },
			{ "name": "X_AT", "type": "string", "value": "X @", "options": "-inr" },
			{ "name": "XECUTE_AT", "type": "string", "value": "XECUTE @", "options": "-inr" },
			{ "name": "IP_ADDRESS ", "type": "string", "value": "IP ADDRESS", "options": "-inr" },
			{ "name": "GMPLUTL", "type": "string", "value": "GMPLUTL", "options": "-inr" },
			{ "name": "D_DIE", "type": "string", "value": "D ^DIE", "options": "-inr" },
			{ "name": "D_DIC", "type": "string", "value": "D ^DIC", "options": "-inr" },
			{ "name": "4-DIE_ETC", "type": "string", "value": "\"\"(FOR ^DIE,ETC.)\"\"", "options": "-inr" },
			{ "name": "UPDATE", "type": "string", "value": "UPDATE^", "options": "-inr" },
			{ "name": "FILE", "type": "string", "value": "FILE^", "options": "-inr" },
			{ "name": "Update_File", "type": "string", "value": "\",UPDATE^ - FILE^\"", "options": "-inr" },
			{ "name": "S_UP", "type": "string", "value": "S ^", "options": "-inr" },
			{ "name": "ADDRESS", "type": "string", "value": "ADDRESS", "options": "-inr" },
			{ "name": "ADR", "type": "string", "value": "ADR", "options": "-inr" },
			{ "name": "AUTHENTICATED", "type": "string", "value": "AUTHENTICATED", "options": "-inr" },
			{ "name": "AUTHENTICATE", "type": "string", "value": "AUTHENTICATE", "options": "-inr" },
			{ "name": "AUTHENTICATION", "type": "string", "value": "AUTHENTICATION", "options": "-inr" },
			{ "name": "AUTHORIZATION", "type": "string", "value": "AUTHORIZATION", "options": "-inr" },
			{ "name": "BACKDOOR", "type": "string", "value": "BACKDOOR", "options": "-inr" },
			{ "name": "CACHE", "type": "string", "value": "CACHE", "options": "-inr" },
			{ "name": "Cache", "type": "string", "value": "Cache", "options": "-inr" },
			{ "name": "Caché", "type": "string", "value": "Caché", "options": "-inr" },
			{ "name": "CERTIFICATE", "type": "string", "value": "CERTIFICATE", "options": "-inr" },
			{ "name": "Certifier", "type": "string", "value": "Certifier", "options": "-inr" },
			{ "name": "CONNECT", "type": "string", "value": "CONNECT", "options": "-inr" },
			{ "name": "COOKIE", "type": "string", "value": "COOKIE", "options": "-inr" },
			{ "name": "CREDENTIALS", "type": "string", "value": "CREDENTIALS", "options": "-inr" },
			{ "name": "DECODE", "type": "string", "value": "DECODE", "options": "-inr" },
			{ "name": "DECRYPT", "type": "string", "value": "DECRYPT", "options": "-inr" },
			{ "name": "DEVICE", "type": "string", "value": "DEVICE", "options": "-inr" },
			{ "name": "DIGITAL", "type": "string", "value": "DIGITAL", "options": "-inr" },
			{ "name": "EMBEDDED", "type": "string", "value": "EMBEDDED", "options": "-inr" },
			{ "name": "ENCRYPT", "type": "string", "value": "ENCRYPT", "options": "-inr" },
			{ "name": "GATEWAY", "type": "string", "value": "GATEWAY", "options": "-inr" },
			{ "name": "HANDSHAKE", "type": "string", "value": "HANDSHAKE", "options": "-inr" },
			{ "name": "HASHING", "type": "string", "value": "HASHING", "options": "-inr" },
			{ "name": "HL7", "type": "string", "value": "HL7", "options": "-inr" },
			{ "name": "IDENTIFIER", "type": "string", "value": "IDENTIFIER", "options": "-inr" },
			{ "name": "IDENTITY", "type": "string", "value": "IDENTITY", "options": "-inr" },
			{ "name": "INITALIZE", "type": "string", "value": "INITALIZE", "options": "-inr" },
			{ "name": "IP", "type": "string", "value": "IP", "options": "-inr" },
			{ "name": "MRN", "type": "string", "value": "MRN", "options": "-inr" },
			{ "name": "NETWORK", "type": "string", "value": "NETWORK", "options": "-inr" },
			{ "name": "PASSWORD", "type": "string", "value": "PASSWORD", "options": "-inr" },
			{ "name": "PWD", "type": "string", "value": "PWD", "options": "-inr" },
			{ "name": "PORT", "type": "string", "value": "PORT", "options": "-inr" },
			{ "name": "PROXY", "type": "string", "value": "PROXY", "options": "-inr" },
			{ "name": "PUBLIC", "type": "string", "value": "PUBLIC", "options": "-inr" },
			{ "name": "REMOTE", "type": "string", "value": "REMOTE", "options": "-inr" },
			{ "name": "Responder", "type": "string", "value": "Responder", "options": "-inr" },
			{ "name": "REVOKE", "type": "string", "value": "REVOKE", "options": "-inr" },
			{ "name": "SCANNING", "type": "string", "value": "SCANNING", "options": "-inr" },
			{ "name": "SIGNATURE", "type": "string", "value": "SIGNATURE", "options": "-inr" },
			{ "name": "SOCIAL", "type": "string", "value": "SOCIAL", "options": "-inr" },
			{ "name": "SSN", "type": "string", "value": "SSN", "options": "-inr" },
			{ "name": "SOCKET", "type": "string", "value": "SOCKET", "options": "-inr" },
			{ "name": "SOCK", "type": "string", "value": "SOCK", "options": "-inr" },
			{ "name": "TCP", "type": "string", "value": "TCP", "options": "-inr" },
			{ "name": "TOKEN", "type": "string", "value": "TOKEN", "options": "-inr" },
			{ "name": "TOK", "type": "string", "value": "TOK", "options": "-inr" },
			{ "name": "TRACKING", "type": "string", "value": "TRACKING", "options": "-inr" },
			{ "name": "TRANSMISSION", "type": "string", "value": "TRANSMISSION", "options": "-inr" },
			{ "name": "UNAUTHORIZED", "type": "string", "value": "UNAUTHORIZED", "options": "-inr" },
			{ "name": "VERSION", "type": "string", "value": "VERSION", "options": "-inr" }
		];
	console.log(`There are ${vArray.length} vulnerabilities`);
	return vArray;
};

module.exports = Vulnerabilities();
