const fs = require('fs-extra');
const url = require('url');
const constants = require("./consts.js");

const getFolderList = function() {
	const PromiseGenFolderListFile = function(rootFolder) {
		return fs.readdir(rootFolder)
			.then(function(files) {
				let relURLs = [];
				// let arrays = [];
				const root = process.cwd();
				files.forEach(function(f) {
					let resol = url.resolve("", f.replace(root, ""));
					relURLs.push(resol);
					// arrays.push(resol);
				})

				// Gen the folder list file here with writestreams
				const scanResultsListFile = fs.createWriteStream(constants.scanResultsListFile);
				scanResultsListFile.write("// Do not change anything in this file.\n");
				scanResultsListFile.write("// Content here is auto generated by the scan process\n");
				scanResultsListFile.write("const scanResultsFolders = [\n");
				let line = 0;
				let buf = "";
				relURLs.forEach(function(x) {
					buf = "";
					if (line++ > 0) {
						buf = ",\n";
					}
					buf += JSON.stringify(x, null, 2);
					scanResultsListFile.write(buf);
				});
				scanResultsListFile.write("\n];\n");

				scanResultsListFile.write("const VulnerabilityList = {};\n");
				relURLs.forEach(function(a) {
					scanResultsListFile.write(`VulnerabilityList.${a} = ${a};\n`);
				});

				return relURLs;
			})
			.catch(function(err) {
				console.log("We got an error - ", err.code);
				return ("PromiseGenFolderListFile - It Broke :(");
			});
	};

	return { PromiseGenFolderListFile }
}();

module.exports = getFolderList;
